---
sidebar: sidebar 
permalink: doc-gen-ai-assistant.html 
keywords: netapp, generative ai, doc 
summary: NetApp生成AIアシスタントドキュメントは、docs.jp.comで入手できますNetApp。デルは、このサイトで公開されているコンテンツのみを使用して、NetApp製品に関する質問に回答します。デルテレフォンアドバイザーは、他のNetAppサイトやパブリックインターネットのコンテンツを使用して質問に回答することはありません。 
---
= NetAppジェネレーティブAIを活用したアシスタントの概要
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp生成AIアシスタント「Doc」はdocs.jpから入手できますNetApp。デルは、このサイトで公開されているコンテンツのみを使用して、NetApp製品に関する質問に回答します。デルテレフォンアドバイザーは、他のNetAppサイトやパブリックインターネットのコンテンツを使用して質問に回答することはありません。



== 機能

* ドクは象ではなく、かなりの記憶力を持っている。
+
ほとんどの場合、Docはあなたが話し合っていることを覚えており、注意を払っています。ドキュメントが会話のトラックを失った場合は、同じチャットセッションで新しい会話を開始できます。

* ドクは熱心な読者だ。
+
私たちのドキュメントがdocs.netapp.comで公開されるたびに(そしてそれは多くのことが起こります)、Docはそれらを読み、それらを参照して応答を生成することができます。ドクの学習の速さには驚かされる。

* デルテレフォンアドバイザーはコンサルタントです。
+
DOCは、あなたが尋ねた質問に加えて、あなたが尋ねたいと思うかもしれない質問の提案を提供します。

* ドクはコミュニケーションをとっています。
+
デルテレフォンアドバイザーは、回答をどのように生成するかについての洞察を共有し、質問の言い換えをする機会を提供します。





== 制限事項

* ドキュメントは、docs.jp.comで公開されたコンテンツのみを使用してNetAppアンサーを生成します。デルテレフォンアドバイザーは、他のNetApp Webサイトで公開されているコンテンツから回答を生成しません。
* ベータ版では、ドキュメントがすべてのNetApp製品のすべてのドキュメントを参照しているわけではありません。ドキュメントとは、回答の生成に役立つONTAP、BlueXP 、StorageGRID、Keystone、SnapCenterのドキュメントを含むがこれらに限定されない、一部のドキュメントのみを指します。ドキュメントが知らない情報をお探しの場合は、mailto：ng-doccoments @ NetApp .com [お知らせください]。
* NetApp製品に複数のバージョンのドキュメントがある場合、ドキュメントは回答を生成するために最新バージョンのみを参照します。
* デルテレフォンアドバイザーは、お客様が興味を持っている製品について想定しているページを参照することはありません。製品名とバージョンについては、できるだけ具体的に質問してください。
* ドキュメントは他の言語で回答を提供できますが、ドキュメントは英語以外のバージョンのNetApp製品ドキュメントを読んでいません。できるだけ正確な情報を得るために、必ずドキュメントの回答を英語で確認してください。




== ヒント

* ドクは具体的な質問が大好きです。
+
DOCでは、製品名、インターフェイス（GUIやAPIなど）、バージョンを明示的に指定すると、より適切な応答が得られます。例：_ ONTAP 9.8からONTAP 9.12.1にアップグレードするには、System Managerでどのような手順に従う必要がありますか？_

* 何かをする方法を学ぶ必要がありますか?
+
手順を含めるようにDocに依頼することを検討します。Doc_インターネットなしでBlueXP  Connectorをインストールするにはどうすればよいですか?_質問_インターネットなしでBlueXP  Connectorをインストールするには、どのような手順を実行する必要がありますか?_

* 簡単な質問をする。
+
複雑な質問をする必要がある場合は、それを小さな質問に分割します(これはチェーン質問と呼ばれることがあります)。チャットセッション中、Docは注意を払い、あなたが尋ねた質問を覚えています。

+
Doc _ BlueXP  でランサムウェア対策とバックアップスケジュールを設定するにはどうすればよいですか?_ try _ BlueXP  でランサムウェア対策を設定する手順は何ですか?_ and _ BlueXP  でバックアップスケジュールを設定する手順は何ですか?_

* 引用符を使用して、Docが誤って解釈する可能性のある複数の単語のフレーズに注意を払う必要がある場合を明確にします。
+
たとえば、Doc _ Storage EfficiencyはONTAPでどのように計算されますか?_ Storage Efficiencyについて質問していると、関連性のない2つの単語として考えられる可能性があります。お客様がStorage Efficiency（Storage Efficiencyという概念）について尋ねていることを確実にDocが理解できるように、このフレーズを引用符で囲んで次のように囲みます。_ ONTAPで「Storage Efficiency」はどのように計算されますか？_

+
人間と会話している場合は、フレーズを強調したり、エアクォートを使用したり、区別を明確にする何らかの方法でジェスチャーを使用したりする可能性があります。二重引用符は、あなたが話していることをDocが理解するのに役立つジェスチャーであると考えてください。

* 回答後、Docはどのように回答を生成したかについての洞察を提供します。興味を持ってください。
+
質問する際には、さまざまなパターンやアプローチを試してみてください。目的の結果が得られない場合は、質問を言い換えてみてください。





== フィードバック

私たちは、Docsの継続的な改善に取り組んでいます。Doc'sチャットウィンドウ内でフィードバックを送信してください。Doc'sの回答が正確で有用であるか、不完全であるか、または何らかの形で不十分であるかどうかをお知らせください。また、DOCの能力や回答に関する質問や懸念がある場合は、ng-doccoments@netapp.com [お問い合わせ]までメールでお問い合わせください。
