---
sidebar: sidebar 
permalink: doc-gen-ai-assistant.html 
keywords: netapp, generative ai, doc 
summary: docs.netapp.comでは、AIを活用したジェネレーティブアシスタントを務めています。ドキュメントは、docs.jp.comで公開されているコンテンツを使用して、NetApp製品に関する質問に回答するように設計されてNetAppいます。 
---
= NetAppジェネレーティブAIを活用したアシスタントの概要
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
docs.netapp.comでは、AIを活用したジェネレーティブアシスタントを務めています。ドキュメントは、docs.jp.comで公開されているコンテンツを使用して、NetApp製品に関する質問に回答するように設計されてNetAppいます。

デルテレフォンアドバイザーは、以前の質問から回答を作成し、追加の質問を提案し、それがどのように回答を生成するかを説明できます。これにより、NetAppのドキュメントをナビゲートするための便利なツールとなります。



== 範囲と制限事項

ドキュメントは、docs.jp.comに公開されている一部のコンテンツに基づいて質問にのみ回答できますNetApp。


NOTE: ベータ版期間中、Docはdocs.netapp.comに掲載されているほとんどのコンテンツ（すべてではない）を使用して質問に回答します。DocはONTAP、 BlueXP、 StorageGRID、Eシリーズ、 Keystone、 SnapCenterのすべてのドキュメントに精通しており、それらを使用して質問に回答します。一方、Docは一部のレガシー製品のドキュメントに精通していません。例えば、DocはSnapDrive for UNIXのドキュメントを使用して回答することはありません。ベータ版期間中、私たちはDocの知識を洗練させるよう取り組んでいます。Docが持っていない情報が必要な場合は、mailto:ng-doccomments@netapp.comまでご連絡ください。

* Doc は、製品の最新の公開バージョンのみに基づいて質問に回答します。例えば、製品のバージョン 1.0 とバージョン 2.0 のドキュメントがある場合、Doc は最新のバージョン 2.0 のドキュメントのみを参照します。
* 最良の結果を得るには、製品名を常に具体的に指定してください。Docは質問時にあなたがどのページにいるかを認識していますが、これは回答を作成する際にDocが考慮するいくつかの要素の1つにすぎません。
* ドキュメントは、docs.jp.comでサポートされている言語でチャットできますNetAppが、英語以外のバージョンではトレーニングされていません。




== 適切なプロンプトを書く

Docsを最大限に活用するには、以下のヒントに従ってください。

具体的な質問をする。:: 詳細な質問を作成し、製品名、バージョン、インターフェイスタイプ（GUI、API）を指定します。例：
+
--
[]
====
ONTAP 9.8からONTAP 9.12.1にアップグレードするには、System Managerでどのような手順を実行する必要がありますか。

====
--
タスクを完了するための手順を尋ねる。:: プロセスを完了するための手順を記載するようにDocに依頼します。インターネットを使用せずにBlueXP  コネクタをインストールする方法を_尋ねる代わりに_お試しください：
+
--
[]
====
インターネットを使用せずにBlueXP  Connectorをインストールするには、どのような手順を実行する必要がありますか？

====
--
複雑な問題を複数のブロックに分割します。:: 複雑な質問を小さな質問に分割します（_chaining_とも呼ばれます）。お客様がチャットを続けると、以前の質問を記憶し、より複雑な回答を作成します。
+
--
たとえば、Doc_How do I configure ransomware protection and backup schedules in BlueXP ？_ try：

[]
====
BlueXP  でランサムウェア対策を設定する手順は何ですか？

====
質問：

[]
====
BlueXP  でバックアップスケジュールを設定する手順を教えてください。

====
--
引用符を使用します。:: 複数の単語を含むフレーズは引用符で囲みます。これは、Docがこのフレーズを単一の概念として認識するのに役立ちます。これは、人間との会話で強調する方法と似ています。
+
--
たとえば、この質問では、ONTAPでストレージ効率はどのように計算されますか？_Docは、「about_storage_and_efficiency_」という2つの関連しない単語を質問していると考えるかもしれません。代わりに次の操作を実行

[]
====
ONTAPでは、「Storage Efficiency」はどのように計算されますか。

====
--
Docの対応を確認します。:: 回答後、Docはどのように回答を生成したかについての洞察を提供します。これは、あなたが望む結果を得るために質問を絞り込む方法のアイデアを与えることができます。
チャット履歴をクリアする:: トピックを変更したい場合（例えば、別の製品について質問したい場合など）、チャット履歴を消去して新しいセッションを開始してください。新しいトピックを開始する前にチャットを消去しないと、正確な結果が得られない可能性があります。




== フィードバック

私たちは、Docsの継続的な改善に取り組んでいます。Doc'sチャットウィンドウ内でフィードバックを送信してください。Doc'sの回答が正確で有用であるか、不完全であるか、または何らかの形で不十分であるかどうかをお知らせください。ドキュメントの機能や回答に関してご質問や懸念がある場合は、mailto：ng-doccomments @ NetApp .com [お問い合わせ]までご連絡ください。
