---
sidebar: sidebar 
permalink: doc-gen-ai-assistant.html 
keywords: netapp, generative ai, doc 
summary: DOCは、docs.jp.comで利用可能なNetApp AIアシスタントですNetApp。このサイトのコンテンツのみを使用して質問に回答します。DOCは、他のNetAppサイトやパブリックインターネットのコンテンツを使用して質問に回答しません。 
---
= NetAppジェネレーティブAIを活用したアシスタントの概要
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
DOCは、docs.jp.comで利用可能なNetApp AIアシスタントですNetApp。このサイトのコンテンツのみを使用して質問に回答します。DOCは、他のNetAppサイトやパブリックインターネットのコンテンツを使用して質問に回答しません。

デルテレフォンアドバイザーは、以前の質問から回答を作成し、追加の質問を提案し、それがどのように回答を生成するかを説明できます。これにより、NetAppのドキュメントをナビゲートするための便利なツールとなります。



== 範囲と制限事項

ドキュメントは、docs.jp.comに公開されている一部のコンテンツに基づいて質問にのみ回答できますNetApp。


NOTE: このベータ段階では、ドキュメントはすべてのdocs.doc.com NetAppコンテンツのトレーニングを受けていません。デルテレフォンアドバイザーは、ONTAP、BlueXP 、StorageGRID、Keystone、SnapCenterなどのコンテンツに関する質問に答えることができます。ドキュメントにない情報が必要な場合は、お知らせください。

* 製品バージョンを指定しない場合、Docは最新の公開バージョンに基づいて質問に答えます。必要に応じて、質問に以前のバージョンを指定できます。
* あなたが質問をするとき、先生はあなたがどのページにいるかを知りません。最適な結果を得るには、製品名とバージョンを指定してください。
* ドキュメントは、docs.jp.comでサポートされている言語でチャットできますNetAppが、英語以外のバージョンではトレーニングされていません。




== 適切なプロンプトを書く

Docsを最大限に活用するには、以下のヒントに従ってください。

具体的な質問をする。:: 詳細な質問を作成し、製品名、バージョン、インターフェイスタイプ（GUI、API）を指定します。例：
+
--
[]
====
ONTAP 9.8からONTAP 9.12.1にアップグレードするには、System Managerでどのような手順を実行する必要がありますか。

====
--
タスクを完了するための手順を尋ねる。:: プロセスを完了するための手順を記載するようにDocに依頼します。インターネットを使用せずにBlueXP  コネクタをインストールする方法を_尋ねる代わりに_お試しください：
+
--
[]
====
インターネットを使用せずにBlueXP  Connectorをインストールするには、どのような手順を実行する必要がありますか？

====
--
複雑な問題を複数のブロックに分割します。:: 複雑な質問を小さな質問に分割します（_chaining_とも呼ばれます）。お客様がチャットを続けると、以前の質問を記憶し、より複雑な回答を作成します。
+
--
たとえば、Doc_How do I configure ransomware protection and backup schedules in BlueXP ？_ try：

[]
====
BlueXP  でランサムウェア対策を設定する手順は何ですか？

====
質問：

[]
====
BlueXP  でバックアップスケジュールを設定する手順を教えてください。

====
--
引用符を使用します。:: 複数の単語を含むフレーズは引用符で囲みます。これは、Docがこのフレーズを単一の概念として認識するのに役立ちます。これは、人間との会話で強調する方法と似ています。
+
--
たとえば、この質問では、ONTAPでストレージ効率はどのように計算されますか？_Docは、「about_storage_and_efficiency_」という2つの関連しない単語を質問していると考えるかもしれません。代わりに次の操作を実行

[]
====
ONTAPでは、「Storage Efficiency」はどのように計算されますか。

====
--
Docの対応を確認します。:: 回答後、Docはどのように回答を生成したかについての洞察を提供します。これは、あなたが望む結果を得るために質問を絞り込む方法のアイデアを与えることができます。
チャット履歴をクリアする:: トピックを変更する場合は、新規開始時にチャットをクリアしてください。Docは以前の質問を覚えているため、トピックの変更によって予期しない結果が生じる可能性があります。




== フィードバック

お寄せいただいたフィードバックは、Docの対応の改善に役立てさせていただきます。ドキュメントチャットウィンドウのフィードバックツールを使用して、回答が正確で有用であるかどうか、または改善が必要であるかどうかをお知らせします。ご質問やご意見がございましたら、mailto：NetApp .comまでEメールでお問い合わせください。
