---
sidebar: sidebar 
permalink: doc-gen-ai-assistant-terms-of-use.html 
keywords:  
summary: docs.netapp.comでは、AIを活用したジェネレーティブアシスタントを務めています。ドキュメントは、docs.jp.comで公開されているコンテンツを使用して、NetApp製品に関する質問に回答するように設計されてNetAppいます。たとえば、NetAppのストレージ効率化機能や、マルチクラウド環境におけるバックアップとリカバリのベストプラクティスに関する質問に対応できます。 
---
= NetAppジェネレーティブAIを活用したアシスタントの利用規約
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
docs.netapp.comでは、AIを活用したジェネレーティブアシスタントを務めています。ドキュメントは、docs.jp.comで公開されているコンテンツを使用して、NetApp製品に関する質問に回答するように設計されてNetAppいます。たとえば、NetAppのストレージ効率化機能や、マルチクラウド環境におけるバックアップとリカバリのベストプラクティスに関する質問に対応できます。

このDocのベータ版では、エラーや不正確さが含まれている可能性のあるアルゴリズムで生成されたコンテンツが作成されます。生成されたすべてのコンテンツは、開始点としてのみ使用する必要があります。必ずネットアップの公式製品ドキュメントを参照して、ドキュメントの回答を確認してください。ドキュメントが生成した回答に依存することはお客様自身の責任であり、NetAppは、ドキュメントが生成した回答のみを使用することによって発生する可能性のある問題や問題については責任を負いません。



== 条件

DOCを使用することにより、コンテンツおよび回答を生成する際に、以下の規則および規定を遵守することに同意したものとみなされます。これらの条件を遵守しないと、Docsの使用がブロックされる可能性があります。

* 害、虐待、暴力、または欺瞞を引き起こす可能性のあるコンテンツを作成するためにDocを使用しようとしないでください。
* 意図された目的の範囲外の会話にドキュメントを関与させたり、NetApp製品以外の質問に対する回答を得たりしないでください。




== フィードバック

私たちは、Docsの継続的な改善に取り組んでいます。Doc'sチャットウィンドウ内でフィードバックを送信してください。Doc'sの回答が正確で有用であるか、不完全であるか、または何らかの形で不十分であるかどうかをお知らせください。また、DOCの能力や回答に関する質問や懸念がある場合は、ng-doccoments@netapp.com [お問い合わせ]までメールでお問い合わせください。
