---
sidebar: sidebar 
permalink: docs-netapp-com.html 
keywords:  
summary:  
---
= docs.netapp.comサイトについて
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


.サイトツアー
video::77a636ba-4202-45bb-9e47-b08a01138502[panopto]
.トランスクリプト
[%collapsible]
====
0：01:: こんにちは。docs.netapp.comチームのベンですこのビデオでは、コンテンツの視聴体験を最大限に活用するために、docs.netapp.comで利用可能な機能について説明します。
0：12:: 探しているコンテンツを見つけることから始めましょう。ドキュメントサイトを入力したら、サイトの左側を使用してナビゲートできます。
0：20:: 複数のバージョンのドキュメントがある場合は、使用している製品のバージョンに対応するドキュメントを選択できます。
0：28:: ドキュメントサイト内のコンテンツを検索するには、検索ボックスを使用します。たとえば、ボリューム暗号化の仕組みを確認したいとします。
0：36:: ドキュメントを参照する場合は、目次を使用できます。目次は、製品の使用開始や使用などの論理的なグループに編成されています。
0：45:: 別のドキュメントサイトにアクセスしたい場合は、パンくずリストを使用してdocs.netapp.comをナビゲートできます。
0：50:: 探しているコンテンツを見つけたら、コンテンツを操作するのに役立ついくつかの主要な機能を利用できます。
0：58:: ほとんどのドキュメントサイトには複数の言語が用意されているため、お好みの言語でドキュメントを読むことができます。
1：05:: ページに複数のセクションがある場合は、[このページ上]リンクを使用して、探しているコンテンツに直接移動できます。リンクには、ページのどこにいるかも示されます。これは、スクロールしながら進むのに役立ちます。
1：20:: コンテンツ自体に焦点を当てるために、左右のサイドバーを折りたたむことができます。完了したら、それらを展開してナビゲーションコントロールを再度表示します。
1：33:: ドキュメントをオフラインで読む必要がある場合は、ドキュメントサイト全体またはサイト内の個 々 のセクションのPDFをダウンロードできます。
1：41:: NetAppのドキュメントはオープンソースであり、GitHubアカウントを使用したコミュニティへの貢献を可能にするように設計されています。フィードバックを送信して、ドキュメントの更新をリクエストするか、コンテンツを直接編集してください。コンテンツは、マージ前にNetAppコンテンツリードに送信されます。
1：59:: ネットアップの一部のクラウドサービスのドキュメントサイトには、特定のクラウドプロバイダにドキュメントをフィルタリングできるクラウドプロバイダオプションが表示される場合があります。たとえば、[Microsoft Azure]を選択した場合、環境Azureというコンテンツのみが表示されます。他のクラウドプロバイダのコンテンツは表示されません。
2：18:: タブレット、モバイルデバイス、またはデスクトップからコンテンツにアクセスする可能性があるため、レスポンシブレイアウトを使用して、ドキュメントがどのデバイスでも見栄えがするようにしています。
2：28:: それだけです。これらの機能をご利用いただき、弊社のコンテンツコミュニティにご参加いただきありがとうございます。


====